# Generated by Django 3.2 on 2022-10-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adressen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=50)),
                ('nachname', models.CharField(max_length=50)),
                ('strasse', models.CharField(max_length=50)),
                ('plz', models.IntegerField()),
                ('ort', models.CharField(max_length=100)),
            ],
        ),
    ]
